### ISSUE TITLE
PS3 controller issues

### ISSUE THREAD

**Issue by artanin** [Kaldaien/PrettyPrinny#3]
Using 3x with the xinput wrapper turned off, and i lost my dpad.  If i leave the wrapper on I get neither the analog or the dpad.  Using https://github.com/nefarius/ScpToolkit over bluetooth.

Thanks!

**Comment by Stormsorter** [comment]
Did you also delete pad.cfg? It stores key and controller bindings and the one that comes with P.P. is for Steam Controller. If you have deleted pad.cfg are you sure its not an issue with SCP or its settings? 

I'm using a PS3 controller over bluetooth with Better DS3 set as a 360 controller and have no issues other than dinput.dll crashing the game if the controller turns off with the game running. If I remember correctly I saw others in the Steam forums mention the same issue without PrettyPrinny and using real 360 controllers so I don't think this has anything to do with PrettyPrinny.

**Comment by artanin** [comment]
Yes, I did try that. I cant use motionjoy/better ds3 as I cant get it to
install anymore.  Just as a random test I reinstalled the whole scp driver
stack and that seems to have fixed it.. Strange sense I never touch the
settings.  Thanks for the help and the effort anyways!

**Comment by Kaldaien** [comment]
If you deleted pad.cfg and set WrapXInput=false, then this cannot be blamed on the mod to the best of my knowledge.

I will leave the issue open for a while, let me know if you manage to resolve it yourself or if 0.4.0's changes do anything to help.
